import { DeviceFrame } from '../types/mockup';

export const DEVICES: DeviceFrame[] = [
  {
    id: 'iphone-15',
    name: 'iPhone 15 Pro',
    category: 'Phone',
    screenW: 393,
    screenH: 852,
    bezelTop: 14,
    bezelBottom: 14,
    bezelSide: 14,
    borderRadius: 50,
    screenRadius: 40,
    hasNotch: false,
    hasDynamicIsland: true,
    hasHomeBar: true,
  },
  {
    id: 'iphone-se',
    name: 'iPhone SE',
    category: 'Phone',
    screenW: 375,
    screenH: 667,
    bezelTop: 60,
    bezelBottom: 60,
    bezelSide: 12,
    borderRadius: 40,
    screenRadius: 0,
    hasNotch: false,
    hasDynamicIsland: false,
    hasHomeBar: false,
  },
  {
    id: 'pixel',
    name: 'Pixel 8',
    category: 'Phone',
    screenW: 412,
    screenH: 915,
    bezelTop: 12,
    bezelBottom: 12,
    bezelSide: 10,
    borderRadius: 36,
    screenRadius: 28,
    hasNotch: false,
    hasDynamicIsland: false,
    hasHomeBar: true,
  },
  {
    id: 'ipad',
    name: 'iPad Pro',
    category: 'Tablet',
    screenW: 820,
    screenH: 1180,
    bezelTop: 20,
    bezelBottom: 20,
    bezelSide: 20,
    borderRadius: 24,
    screenRadius: 10,
    hasNotch: false,
    hasDynamicIsland: false,
    hasHomeBar: false,
  },
  {
    id: 'macbook',
    name: 'MacBook Pro',
    category: 'Laptop',
    screenW: 1440,
    screenH: 900,
    bezelTop: 28,
    bezelBottom: 0,
    bezelSide: 12,
    borderRadius: 14,
    screenRadius: 8,
    hasNotch: true,
    hasDynamicIsland: false,
    hasHomeBar: false,
  },
  {
    id: 'browser',
    name: 'Browser',
    category: 'Web',
    screenW: 1280,
    screenH: 800,
    bezelTop: 40,
    bezelBottom: 0,
    bezelSide: 0,
    borderRadius: 12,
    screenRadius: 0,
    hasNotch: false,
    hasDynamicIsland: false,
    hasHomeBar: false,
  },
  {
    id: 'none',
    name: 'No Frame',
    category: 'Other',
    screenW: 800,
    screenH: 600,
    bezelTop: 0,
    bezelBottom: 0,
    bezelSide: 0,
    borderRadius: 16,
    screenRadius: 16,
    hasNotch: false,
    hasDynamicIsland: false,
    hasHomeBar: false,
  },
];

export const BACKGROUNDS = [
  { id: 'gradient-1', label: 'Ocean', type: 'gradient' as const, value: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' },
  { id: 'gradient-2', label: 'Sunset', type: 'gradient' as const, value: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)' },
  { id: 'gradient-3', label: 'Forest', type: 'gradient' as const, value: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)' },
  { id: 'gradient-4', label: 'Peach', type: 'gradient' as const, value: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)' },
  { id: 'gradient-5', label: 'Night', type: 'gradient' as const, value: 'linear-gradient(135deg, #0c0c1d 0%, #1a1a3e 50%, #2d1b69 100%)' },
  { id: 'gradient-6', label: 'Mint', type: 'gradient' as const, value: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)' },
  { id: 'gradient-7', label: 'Ember', type: 'gradient' as const, value: 'linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)' },
  { id: 'gradient-8', label: 'Slate', type: 'gradient' as const, value: 'linear-gradient(135deg, #e2e2e2 0%, #c9d6ff 100%)' },
  { id: 'solid-1', label: 'White', type: 'solid' as const, value: '#ffffff' },
  { id: 'solid-2', label: 'Black', type: 'solid' as const, value: '#111111' },
  { id: 'solid-3', label: 'Cream', type: 'solid' as const, value: '#F4F0EA' },
  { id: 'mesh-1', label: 'Aurora', type: 'mesh' as const, value: 'radial-gradient(at 40% 20%, #4facfe 0px, transparent 50%), radial-gradient(at 80% 0%, #fee140 0px, transparent 50%), radial-gradient(at 0% 50%, #fa709a 0px, transparent 50%), radial-gradient(at 80% 50%, #30cfd0 0px, transparent 50%), radial-gradient(at 0% 100%, #a18cd1 0px, transparent 50%)' },
  { id: 'mesh-2', label: 'Nebula', type: 'mesh' as const, value: 'radial-gradient(at 20% 80%, #764ba2 0px, transparent 50%), radial-gradient(at 80% 20%, #667eea 0px, transparent 50%), radial-gradient(at 50% 50%, #f093fb 0px, transparent 50%)' },
];

export function getDevice(id: string): DeviceFrame {
  return DEVICES.find((d) => d.id === id) || DEVICES[0];
}
